export const mockVictimRow = {
  id: "test-uuid-001",
  slug: "amini-mahsa-2000",
  name_latin: "Mahsa Amini",
  name_farsi: "مهسا امینی",
  aliases: [],
  date_of_birth: new Date("2000-09-21"),
  place_of_birth: "Saqqez",
  gender: "female",
  ethnicity: "Kurdish",
  religion: null,
  photo_url: "https://storage.googleapis.com/photo.jpg",
  occupation_en: "Student",
  occupation_fa: "دانشجو",
  education: null,
  family_info: null,
  dreams_en: null,
  dreams_fa: null,
  beliefs_en: null,
  beliefs_fa: null,
  personality_en: null,
  personality_fa: null,
  quotes: [],
  date_of_death: new Date("2022-09-16"),
  age_at_death: 22,
  place_of_death: "Tehran",
  province: "Tehran",
  cause_of_death: "Head injuries",
  circumstances_en: "Died in morality police custody",
  circumstances_fa: "در بازداشت گشت ارشاد جان باخت",
  circumstances_de: null,
  event_id: null,
  event_context: null,
  responsible_forces: "Morality Police",
  witnesses: [],
  last_seen: null,
  burial_location: "Aichi Cemetery, Saqqez",
  burial_date: null,
  burial_circumstances_en: null,
  burial_circumstances_fa: null,
  grave_status: null,
  family_persecution_en: null,
  family_persecution_fa: null,
  legal_proceedings: null,
  tributes: [],
  verification_status: "verified",
  data_source: "wikipedia-wlf",
  notes: null,
  created_at: new Date("2026-02-09"),
  updated_at: new Date("2026-02-09"),
};

export const validSubmission = {
  name_latin: "Test Victim",
  details:
    "This is a test submission with enough detail to pass validation minimum.",
};

export const fullSubmission = {
  name_latin: "Test Victim",
  name_farsi: "قربانی آزمایشی",
  date_of_birth: "1990-01-01",
  date_of_death: "2022-09-16",
  place_of_death: "Tehran",
  province: "Tehran",
  cause_of_death: "Gunshot",
  details:
    "Detailed circumstances of the victim's death during protests in Tehran.",
  sources: "https://example.com/source",
  submitter_email: "test@example.com",
  submitter_name: "Test Submitter",
};
